apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: crossplane
type: Opaque
data:
  creds: YXdzX2FjY2Vzc19rZXlfaWQgICAgICAgID0gQVNJQVZBUlpTUlhWVDZTTE9BTkcKYXdzX3NlY3JldF9hY2Nlc3Nfa2V5ICAgID0gYzhUdDN0WXN4V2phMVhiVEFYTkM4WVdOc2NOUVhST293Y0ZjdVdZYQ==